/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReimbursementRouteImport } from './routes/reimbursement'
import { Route as PunchRouteImport } from './routes/punch'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as ExpenseRouteImport } from './routes/expense'
import { Route as EmployeesNewRouteImport } from './routes/employees-new'
import { Route as EmployeesEditRouteImport } from './routes/employees-edit'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DesignationsRouteImport } from './routes/designations'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'

const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReimbursementRoute = ReimbursementRouteImport.update({
  id: '/reimbursement',
  path: '/reimbursement',
  getParentRoute: () => rootRouteImport,
} as any)
const PunchRoute = PunchRouteImport.update({
  id: '/punch',
  path: '/punch',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseRoute = ExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesNewRoute = EmployeesNewRouteImport.update({
  id: '/employees-new',
  path: '/employees-new',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEditRoute = EmployeesEditRouteImport.update({
  id: '/employees-edit',
  path: '/employees-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignationsRoute = DesignationsRouteImport.update({
  id: '/designations',
  path: '/designations',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/departments': typeof DepartmentsRoute
  '/designations': typeof DesignationsRoute
  '/employees': typeof EmployeesRoute
  '/employees-edit': typeof EmployeesEditRoute
  '/employees-new': typeof EmployeesNewRoute
  '/expense': typeof ExpenseRoute
  '/imports': typeof ImportsRoute
  '/leave': typeof LeaveRoute
  '/locations': typeof LocationsRoute
  '/payroll': typeof PayrollRoute
  '/punch': typeof PunchRoute
  '/reimbursement': typeof ReimbursementRoute
  '/reports': typeof ReportsRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/departments': typeof DepartmentsRoute
  '/designations': typeof DesignationsRoute
  '/employees': typeof EmployeesRoute
  '/employees-edit': typeof EmployeesEditRoute
  '/employees-new': typeof EmployeesNewRoute
  '/expense': typeof ExpenseRoute
  '/imports': typeof ImportsRoute
  '/leave': typeof LeaveRoute
  '/locations': typeof LocationsRoute
  '/payroll': typeof PayrollRoute
  '/punch': typeof PunchRoute
  '/reimbursement': typeof ReimbursementRoute
  '/reports': typeof ReportsRoute
  '/travel': typeof TravelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/departments': typeof DepartmentsRoute
  '/designations': typeof DesignationsRoute
  '/employees': typeof EmployeesRoute
  '/employees-edit': typeof EmployeesEditRoute
  '/employees-new': typeof EmployeesNewRoute
  '/expense': typeof ExpenseRoute
  '/imports': typeof ImportsRoute
  '/leave': typeof LeaveRoute
  '/locations': typeof LocationsRoute
  '/payroll': typeof PayrollRoute
  '/punch': typeof PunchRoute
  '/reimbursement': typeof ReimbursementRoute
  '/reports': typeof ReportsRoute
  '/travel': typeof TravelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/auth'
    | '/departments'
    | '/designations'
    | '/employees'
    | '/employees-edit'
    | '/employees-new'
    | '/expense'
    | '/imports'
    | '/leave'
    | '/locations'
    | '/payroll'
    | '/punch'
    | '/reimbursement'
    | '/reports'
    | '/travel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/auth'
    | '/departments'
    | '/designations'
    | '/employees'
    | '/employees-edit'
    | '/employees-new'
    | '/expense'
    | '/imports'
    | '/leave'
    | '/locations'
    | '/payroll'
    | '/punch'
    | '/reimbursement'
    | '/reports'
    | '/travel'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/auth'
    | '/departments'
    | '/designations'
    | '/employees'
    | '/employees-edit'
    | '/employees-new'
    | '/expense'
    | '/imports'
    | '/leave'
    | '/locations'
    | '/payroll'
    | '/punch'
    | '/reimbursement'
    | '/reports'
    | '/travel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DesignationsRoute: typeof DesignationsRoute
  EmployeesRoute: typeof EmployeesRoute
  EmployeesEditRoute: typeof EmployeesEditRoute
  EmployeesNewRoute: typeof EmployeesNewRoute
  ExpenseRoute: typeof ExpenseRoute
  ImportsRoute: typeof ImportsRoute
  LeaveRoute: typeof LeaveRoute
  LocationsRoute: typeof LocationsRoute
  PayrollRoute: typeof PayrollRoute
  PunchRoute: typeof PunchRoute
  ReimbursementRoute: typeof ReimbursementRoute
  ReportsRoute: typeof ReportsRoute
  TravelRoute: typeof TravelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimbursement': {
      id: '/reimbursement'
      path: '/reimbursement'
      fullPath: '/reimbursement'
      preLoaderRoute: typeof ReimbursementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punch': {
      id: '/punch'
      path: '/punch'
      fullPath: '/punch'
      preLoaderRoute: typeof PunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense': {
      id: '/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof ExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees-new': {
      id: '/employees-new'
      path: '/employees-new'
      fullPath: '/employees-new'
      preLoaderRoute: typeof EmployeesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees-edit': {
      id: '/employees-edit'
      path: '/employees-edit'
      fullPath: '/employees-edit'
      preLoaderRoute: typeof EmployeesEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designations': {
      id: '/designations'
      path: '/designations'
      fullPath: '/designations'
      preLoaderRoute: typeof DesignationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  DepartmentsRoute: DepartmentsRoute,
  DesignationsRoute: DesignationsRoute,
  EmployeesRoute: EmployeesRoute,
  EmployeesEditRoute: EmployeesEditRoute,
  EmployeesNewRoute: EmployeesNewRoute,
  ExpenseRoute: ExpenseRoute,
  ImportsRoute: ImportsRoute,
  LeaveRoute: LeaveRoute,
  LocationsRoute: LocationsRoute,
  PayrollRoute: PayrollRoute,
  PunchRoute: PunchRoute,
  ReimbursementRoute: ReimbursementRoute,
  ReportsRoute: ReportsRoute,
  TravelRoute: TravelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
